app = "wg-hub-test"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_GO_TARGETS = "./cmd/wireguard-hub"

[env]
  PORT = "9999"
  DEBUG_PORT = "10000"
  BIND_ADDRESS= "fly-global-services"
  PEER_1 = "h1/wJ5KoQX1fQzQ25rlHb18wgAG80vkDLtn8B7pxOW0=,100.100.0.1/32"
  PEER_2 = "h2/PAmEgoIRLYBDDTL3dZKAOaLEhu4270vlNWXFMSys=,100.100.0.2/32"

[[services]]
  internal_port = 9999
  protocol = "udp"
  [[services.ports]]
    port = 9999

[[services]]
  internal_port = 10000
  protocol = "tcp"
  [[services.ports]]
    port = 10000
