app = "wg-hub-test"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_GO_TARGETS = "./cmd/wg-hub"

[env]
# configure the PRIVATE_KEY using
# flyctl secrets set PRIVATE_KEY="..."
  PORT = "9999"
  DEBUG_SERVER = "true"
  BIND_ADDRESS= "fly-global-services"
  PEER_1 = "h1/wJ5KoQX1fQzQ25rlHb18wgAG80vkDLtn8B7pxOW0=,192.168.0.1/32"
  PEER_2 = "h2/nkfoPYSSno68B0mkbMhxPrn2gCgjelc7N2xSGMiE=,192.168.0.2/32"

[[services]]
  internal_port = 9999
  protocol = "udp"
  [[services.ports]]
    port = 9999
